image: node:latest

stages:
  - production

production:
  type: deploy
  stage: production
  tags:
    - ugrad
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main
