image: node:latest

stages:
  - production

production:
  type: deploy
  stage: production
  tags:
    - ugrad
  image: ruby:latest
  script:
    - sudo apt-get update -qy
    - sudo apt-get install -y ruby-dev
    - sudo gem install dpl
    - sudo dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main
